# Generated by Django 2.0.4 on 2018-04-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('web', models.CharField(max_length=1000)),
            ],
        ),
    ]
